language: node_js
node_js:
  - "10"
script:
  - npm install
  - cd functions && npm install
  - cd webapp && npm run dist
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
